#pragma once
#include <fstream>
#include <functional>
#include <mutex>
#include <string>

// header generated by Bazel from the proto file
#include "kvstore/protos/wal.pb.h"

class WriteAheadLog {
public:
  // Constructor
  explicit WriteAheadLog(const std::string &filename);

  // Destructor; closes file
  ~WriteAheadLog();

  // Appends command to log
  bool Append(const std::string &key, const std::string &value);

  // Reads all entries from the log to restore state
  bool ReadAll(std::function<void(const kvstore::LogEntry &)> visitor);

private:
  std::string filename_;   // Store filename to reopen for reading
  std::ofstream log_file_; // file handler
  std::mutex mu_;          // prevents thread conflicts
};